name: Deploy Nortifi to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22  

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}

            echo "Pulling latest code..."
            git pull origin master

            echo "Installing dependencies..."
            npm install --legacy-peer-deps

            echo "Building frontend..."
            cd frontend
            npm install --legacy-peer-deps
            npm run build
            cd ..

            echo "Restarting PM2..."
            pm2 restart all || pm2 start index.js --name index

            echo "✅ Deployment complete!"
          EOF
